spring:
  mvc:
   view:
    prefix: /pages/
    suffix: .jsp
  datasource: 
   url: jdbc:mysql://localhost:3306/hibernate2mp
   username: root
   password: root 
   driver: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
